
FLAGS = -std=c++17 -Wall -g
INCLUDE = -I ../include

bin/logger.o logger
	g++ $(FLAGS) -o bin/logger.o test_Logger.cpp $(INCLUDE)
bin/time.o time:
	g++ $(FLAGS) -o bin/time.o test_Time.cpp $(INCLUDE)
